@echo off
:: ============================================================================
:: UpdateBuildVersion.bat
:: Auto-generates FB4D\Source\FB4DVersion.inc with the current git commit count
:: as the build number.
::
:: Usage (Delphi Pre-Build Event):
::   "$(PROJECTDIR)\..\..\Scripts\UpdateBuildVersion.bat" "$(PROJECTDIR)\..\.."
::   (adjust the relative path to the FB4D repo root as needed for each project)
::
:: Or call directly from the repo root:
::   Scripts\UpdateBuildVersion.bat .
:: ============================================================================

setlocal

:: --- Determine repo root (first argument, or current dir if not supplied) ---
if "%~1"=="" (
  set REPO_ROOT=%CD%
) else (
  set REPO_ROOT=%~f1
)

set VERSION_FILE=%REPO_ROOT%\Source\FB4DVersion.inc

:: --- Read major/minor/release from existing file so we never overwrite them --
set MAJOR=1
set MINOR=9
set RELEASE=1

for /f "tokens=3 delims=; " %%A in ('findstr "cLibMajorVersion" "%VERSION_FILE%" 2^>nul') do set MAJOR=%%A
for /f "tokens=3 delims=; " %%A in ('findstr "cLibMinorVersion" "%VERSION_FILE%" 2^>nul') do set MINOR=%%A
for /f "tokens=3 delims=; " %%A in ('findstr "cLibReleaseVersion" "%VERSION_FILE%" 2^>nul') do set RELEASE=%%A

:: --- Get commit count from git ---
for /f %%i in ('git -C "%REPO_ROOT%" rev-list --count HEAD 2^>nul') do set BUILD=%%i

if "%BUILD%"=="" (
  echo [UpdateBuildVersion] WARNING: git not found or not a git repo. Build number unchanged.
  exit /b 0
)

:: --- Write the new file ---
(
  echo const
  echo   cLibMajorVersion = %MAJOR%;
  echo   cLibMinorVersion = %MINOR%;
  echo   cLibReleaseVersion = %RELEASE%;
  echo   cLibBuildVersion = %BUILD%; // Auto-generated by Scripts\UpdateBuildVersion.bat
) > "%VERSION_FILE%"

echo [UpdateBuildVersion] FB4DVersion.inc updated: v%MAJOR%.%MINOR%.%RELEASE%.%BUILD%

endlocal
